import { ContextProvider } from "@/context/useContext";
import { Manrope } from "next/font/google";
import { Header } from "@/shared/Header";
import { Footer } from "@/shared/Footer";
import "@/styles/main.css";

const manrope = Manrope({
  weight: ["400", "500", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Nosara Booking Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        <ContextProvider>
        <Header /> 
        {children}
        <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}