import { Manrope } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { Header } from "@/shared/Header";
import { Footer } from "@/shared/Footer";
import "@/styles/main.css";
import { Providers } from "@/context/Providers";

const manrope = Manrope({
  weight: ["400", "500", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Nosara Booking Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        <Providers>
        <Header /> 
        {children}
        <Footer />
        </Providers>
        <Toaster />
      </body>
    </html>
  )}